package io.github.cowwoc.styler.ast.core;

/**
 * Enumeration of all AST node types supported by the parser.
 * Each node type corresponds to a specific Java language construct.
 */
public enum NodeType
{
	// Literals
	INTEGER_LITERAL,
	LONG_LITERAL,
	FLOAT_LITERAL,
	DOUBLE_LITERAL,
	BOOLEAN_LITERAL,
	CHAR_LITERAL,
	STRING_LITERAL,
	NULL_LITERAL,

	// Identifiers and Names
	IDENTIFIER,
	QUALIFIED_NAME,

	// Expressions
	BINARY_EXPRESSION,
	UNARY_EXPRESSION,
	POSTFIX_EXPRESSION,
	ASSIGNMENT_EXPRESSION,
	CONDITIONAL_EXPRESSION,
	INSTANCEOF_EXPRESSION,
	LAMBDA_EXPRESSION,
	METHOD_REFERENCE,
	CAST_EXPRESSION,
	ARRAY_ACCESS,
	FIELD_ACCESS,
	METHOD_INVOCATION,
	PARENTHESIZED_EXPRESSION,
	ARRAY_CREATION,
	OBJECT_CREATION,

	// Statements
	BLOCK,
	EXPRESSION_STATEMENT,
	VARIABLE_DECLARATION,
	IF_STATEMENT,
	FOR_STATEMENT,
	ENHANCED_FOR_STATEMENT,
	WHILE_STATEMENT,
	DO_WHILE_STATEMENT,
	SWITCH_STATEMENT,
	SWITCH_CASE,
	RETURN_STATEMENT,
	THROW_STATEMENT,
	TRY_STATEMENT,
	CATCH_CLAUSE,
	FINALLY_CLAUSE,
	SYNCHRONIZED_STATEMENT,
	BREAK_STATEMENT,
	CONTINUE_STATEMENT,
	ASSERT_STATEMENT,
	EMPTY_STATEMENT,

	// Declarations
	COMPILATION_UNIT,
	PACKAGE_DECLARATION,
	IMPORT_DECLARATION,
	CLASS_DECLARATION,
	INTERFACE_DECLARATION,
	ENUM_DECLARATION,
	ANNOTATION_DECLARATION,
	METHOD_DECLARATION,
	CONSTRUCTOR_DECLARATION,
	FIELD_DECLARATION,
	ENUM_CONSTANT,
	PARAMETER_DECLARATION,

	// Type-related
	TYPE_REFERENCE,
	ARRAY_TYPE,
	PARAMETERIZED_TYPE,
	TYPE_PARAMETER,
	WILDCARD_TYPE,
	PRIMITIVE_TYPE,

	// Annotations
	ANNOTATION,
	ANNOTATION_ELEMENT,

	// Modifiers
	MODIFIERS
}
